### ISSUE TITLE
Don't set proxy when value is either empty or not specified

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/puppet-simianarmy#3]
Currently proxy-related client properties are set when proxy is nil.
However, a number of users have been mixing nil (from not specifying the config properties in the first place) and empty string (by specifying the config properties but setting it to an empty value) in order to indicate that there's no proxy to be used.

In order to handle various user inputs (and humans being humans). The current check should also handle empty string besides nil.

**Comment by Epoxboy** [comment]
PR #4  has been created regarding this issue

**Comment by Epoxboy** [comment]
closed PR # 4 AND created a new PR #5 , it's been tested successfully and ready for merge.
